### ISSUE TITLE
Method not working

### ISSUE THREAD

**Issue by monove** [elizabethrego/cordova-plugin-instabug#2]
I have a Pro account and am getting the following error:

```
Uncaught TypeError: cordova.plugins.instabug.setUserData is not a function
```

I don't get this error for any other Pro features

**Comment by elizabethrego** [comment]
Yes. I received your email. I am working on an urgent deadline and will
resolve this for you as soon as I can. Apologies for the delay. In the
meantime, you may want to look into their API documentation and see if you
can fix it yourself.

**Comment by monove** [comment]
attempted fix: https://github.com/elizabethrego/cordova-plugin-instabug/pull/3
